enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[YouTube-Morphe]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music]
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Music-Morphe]
app-name = "Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Reddit-Morphe]
app-name = "Reddit"
rv-brand = "Morphe"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
dpi = "120-640dpi"

[Twitch]
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "De-Vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"

# [Twitter]
# apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
# uptodown-dlurl = "https://twitter.en.uptodown.com/android"
# dpi = "120-640dpi"

[Twitter]
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Piko"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
# version = "11.81.0-release.0"

[CamScanner]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/intsig-pte/camscanner-phone-pdf-creator/"
uptodown-dlurl = "https://camscanner.en.uptodown.com/android"

# [SolidExplorer]
# apkmirror-dlurl = "https://apkmirror.com/apk/neatbytes/solid-explorer-beta/"
# uptodown-dlurl = "https://solid-explorer-file-manager.en.uptodown.com/android"

[SolidExplorer]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "hoo-dles"
apkmirror-dlurl = "https://apkmirror.com/apk/neatbytes/solid-explorer-beta/"
uptodown-dlurl = "https://solid-explorer-file-manager.en.uptodown.com/android"

[TikTok]
enabled = false
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
included-patches = "'SIM spoof'"

# [Messenger]
# apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
# arch = "arm64-v8a"

[Messenger]
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "De-Vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
arch = "arm64-v8a"
